services:
  postgres:
    image: postgres:16-alpine
    container_name: mockify-postgres
    environment:
      POSTGRES_DB: mockify
      POSTGRES_USER: mockify_user
      POSTGRES_PASSWORD: mockify_password
    ports:
      - "5432:5432"
    volumes:
      - mockify_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mockify-redis
    ports:
      - "6379:6379"
    volumes:
      - mockify_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mockify_data:
  mockify_redis_data: